

class TutorOrchestrator:
    def __init__(
        self,
        vector_manager: type,
        llm_discuss: type
    ):
        """
        Initialises the orchestrator with our existing brain and voice.
        :param vector_manager:  VectorManager class instance
        :param llm_discuss: LLDiscuss class instance
        """
        self.vector_db = vector_manager()
        self.llm = llm_discuss()

    def ask(
        self,
        user_query: str
    ) -> str:
        """
        The core RAG loop: Search -> Format -> Generate.
        :param user_query: The user's query string
        :return: The response generated by the LLM based on retrieved context
        """
        context_chunks = self.vector_db.search(query=user_query, n_results=3)

        if not context_chunks:
            return "I couldn't find any relevant information in your attachment(s)."

        response = self.llm.chat(
            user_query=user_query,
            context_chunks=context_chunks
        )

        return response